package com.nikola.algorithmvisualizer.algorithm;
import java.util.*; import org.springframework.stereotype.Service; import com.nikola.algorithmvisualizer.trace.*;
@Service public class HeapSortAlgorithm extends AbstractSortingAlgorithm {
 public String id(){return "heap";} public AlgorithmInfo info(){return new AlgorithmInfo(id(),"Heap Sort");} public List<MetricType> metricTypes(){return List.of(MetricType.COMPARISONS,MetricType.WRITES,MetricType.SWAPS);}
 public VersionedAlgorithmTrace<EventData> execute(List<Integer> input){var a=items(input);var t=new TraceEventBuilder(MAX_EVENTS);int n=a.size();t.add(SemanticEventType.BUILD_HEAP,"build-heap",a,List.of(),new HeapData(n,0,-1));for(int i=n/2-1;i>=0;i--)heapify(a,n,i,t,List.of());for(int end=n-1;end>0;end--){t.add(SemanticEventType.ROOT_SELECT,"select-root",a,end<n-1?ranges(new SortedRange(end+1,n-1)):List.of(),new HeapData(end+1,0,end));swap(a,0,end,t,end<n-1?ranges(new SortedRange(end+1,n-1)):List.of());var sorted=ranges(new SortedRange(end,n-1));t.add(SemanticEventType.HEAP_SHRINK,"shrink-heap",a,sorted,new HeapData(end,0,end));heapify(a,end,0,t,sorted);}t.add(SemanticEventType.MARK_SORTED,"complete-heap",a,ranges(new SortedRange(0,n-1)),new MarkSortedData(0,n-1));return result(input,a,t);}
 private void heapify(List<TraceItem>a,int n,int root,TraceEventBuilder t,List<SortedRange> sorted){int largest=root;while(true){int left=2*largest+1,right=left+1,candidate=largest;t.add(SemanticEventType.HEAPIFY,"heapify",a,sorted,new HeapData(n,largest,left<n?left:-1));if(left<n){compareEvent(a,candidate,left,t,sorted);if(a.get(left).value()>a.get(candidate).value())candidate=left;}if(right<n){compareEvent(a,candidate,right,t,sorted);if(a.get(right).value()>a.get(candidate).value())candidate=right;}if(candidate==largest)return;swap(a,largest,candidate,t,sorted);largest=candidate;}}
 private void compareEvent(List<TraceItem>a,int x,int y,TraceEventBuilder t,List<SortedRange>s){t.add(SemanticEventType.COMPARE,"compare-child",a,s,new CompareData(List.of(x,y),List.of(a.get(x),a.get(y)),compare(a.get(x),a.get(y))));}
 private void swap(List<TraceItem>a,int x,int y,TraceEventBuilder t,List<SortedRange>s){if(x==y)return;var inds=List.of(x,y);t.add(SemanticEventType.SWAP,"swap-heap",a,s,new SwapData(inds));Collections.swap(a,x,y);t.add(SemanticEventType.WRITE,"write-swap",a,s,new WriteData(inds,List.of(a.get(x),a.get(y))));}
}
