package com.nikola.algorithmvisualizer.algorithm;
import java.util.*; import org.springframework.stereotype.Service; import com.nikola.algorithmvisualizer.trace.*;
@Service public class QuickSortAlgorithm extends AbstractSortingAlgorithm {
 public String id(){return "quick";} public AlgorithmInfo info(){return new AlgorithmInfo(id(),"Quick Sort");} public List<MetricType> metricTypes(){return List.of(MetricType.COMPARISONS,MetricType.WRITES,MetricType.SWAPS);}
 public VersionedAlgorithmTrace<EventData> execute(List<Integer> input){var a=items(input);var t=new TraceEventBuilder(MAX_EVENTS);var finalized=new TreeSet<Integer>();sort(a,0,a.size()-1,t,finalized);if(a.size()==1)t.add(SemanticEventType.MARK_SORTED,"partition-complete",a,ranges(new SortedRange(0,0)),new MarkSortedData(0,0));return result(input,a,t);}
 private void sort(List<TraceItem>a,int l,int r,TraceEventBuilder t,Set<Integer> f){if(l>r)return;if(l==r){f.add(l);t.add(SemanticEventType.MARK_SORTED,"partition-complete",a,toRanges(f),new MarkSortedData(l,l));return;}int p=partition(a,l,r,t,f);f.add(p);t.add(SemanticEventType.PARTITION_COMPLETE,"partition-complete",a,toRanges(f),new PartitionData(l,r,r,p,p));sort(a,l,p-1,t,f);sort(a,p+1,r,t,f);}
 private int partition(List<TraceItem>a,int l,int r,TraceEventBuilder t,Set<Integer>f){TraceItem pivot=a.get(r);int b=l;t.add(SemanticEventType.PIVOT_SELECT,"select-pivot",a,toRanges(f),new PartitionData(l,r,l,b,r));for(int s=l;s<r;s++){t.add(SemanticEventType.PARTITION_ACTIVE,"scan-partition",a,toRanges(f),new PartitionData(l,r,s,b,r));var pair=List.of(a.get(s),pivot);t.add(SemanticEventType.COMPARE,"compare-pivot",a,toRanges(f),new CompareData(List.of(s,r),pair,compare(pair.get(0),pair.get(1))));if(a.get(s).value()<=pivot.value()){swap(a,b,s,t,toRanges(f));b++;}}swap(a,b,r,t,toRanges(f));return b;}
 private void swap(List<TraceItem>a,int x,int y,TraceEventBuilder t,List<SortedRange> ranges){if(x==y)return;var inds=List.of(x,y);t.add(SemanticEventType.SWAP,"swap-partition",a,ranges,new SwapData(inds));Collections.swap(a,x,y);t.add(SemanticEventType.WRITE,"write-swap",a,ranges,new WriteData(inds,List.of(a.get(x),a.get(y))));}
 private List<SortedRange> toRanges(Set<Integer>s){var out=new ArrayList<SortedRange>();Integer start=null,last=null;for(int x:s){if(start==null){start=last=x;}else if(x==last+1)last=x;else{out.add(new SortedRange(start,last));start=last=x;}}if(start!=null)out.add(new SortedRange(start,last));return out;}
}
