import type { KnapsackItem } from '../types'

const presets = [{ label: 'Weekend hike', items: [{ name: 'Map', weight: 1, value: 4 }, { name: 'Compass', weight: 2, value: 5 }], capacity: 3 }, { label: 'Camera bag', items: [{ name: 'Camera', weight: 3, value: 8 }, { name: 'Lens', weight: 2, value: 6 }, { name: 'Tripod', weight: 4, value: 7 }], capacity: 5 }]

export function KnapsackAuthoring({ items, capacity, changed, onItemsChange, onCapacityChange, onRun }: { items: KnapsackItem[]; capacity: string; changed: boolean; onItemsChange: (items: KnapsackItem[]) => void; onCapacityChange: (capacity: string) => void; onRun: () => void }) {
  const draftItems = Array.isArray(items) ? items : []
  function update(index: number, field: keyof KnapsackItem, value: string) { onItemsChange(draftItems.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: field === 'name' ? value : Number(value) } : item)) }
  return <div className="knapsack-authoring"><div className="presets" aria-label="Knapsack presets">{presets.map(preset => <button key={preset.label} type="button" onClick={() => { onItemsChange(preset.items); onCapacityChange(String(preset.capacity)) }}>{preset.label}</button>)}</div><div className="knapsack-item-rows">{draftItems.map((item, index) => <fieldset key={index}><legend>Item {index + 1}</legend><label>Item {index + 1} name<input value={item.name} onChange={event => update(index, 'name', event.target.value)} /></label><label>Item {index + 1} weight<input inputMode="numeric" value={item.weight} onChange={event => update(index, 'weight', event.target.value)} /></label><label>Item {index + 1} value<input inputMode="numeric" value={item.value} onChange={event => update(index, 'value', event.target.value)} /></label>{draftItems.length > 1 && <button type="button" onClick={() => onItemsChange(draftItems.filter((_, itemIndex) => itemIndex !== index))}>Remove item {index + 1}</button>}</fieldset>)}</div><div className="input-row"><button type="button" onClick={() => onItemsChange([...draftItems, { name: '', weight: 1, value: 0 }])} disabled={draftItems.length >= 10}>Add item</button><label htmlFor="knapsack-capacity">Capacity</label><input id="knapsack-capacity" inputMode="numeric" value={capacity} onChange={event => onCapacityChange(event.target.value)} /><button className="button button--run" onClick={onRun}>Visualize Knapsack</button></div>{changed && <p className="draft-changed">Draft changed. Run again to replace the completed playback.</p>}</div>
}
