package com.nikola.algorithmvisualizer.algorithm;
import static org.assertj.core.api.Assertions.assertThat; import java.util.*; import java.util.stream.*; import org.junit.jupiter.params.ParameterizedTest; import org.junit.jupiter.params.provider.MethodSource; import org.junit.jupiter.api.Test; import com.nikola.algorithmvisualizer.trace.*;
class SortingAlgorithmsTests {
 static Stream<SortingAlgorithm<?>> algorithms(){return Stream.of(new InsertionSortAlgorithm(),new SelectionSortAlgorithm(),new BubbleSortAlgorithm(),new MergeSortAlgorithm(),new QuickSortAlgorithm(),new HeapSortAlgorithm());}
 @ParameterizedTest @MethodSource("algorithms") void sortsRequiredInputsAndMaintainsTraceInvariants(SortingAlgorithm<?> algorithm){List<List<Integer>> inputs=new ArrayList<>(List.of(List.of(1),List.of(1,2,3),List.of(3,2,1),List.of(3,1,3,1),List.of(-3,7,-1,-8,4)));inputs.add(IntStream.rangeClosed(1,50).map(i->51-i).boxed().toList());Random random=new Random(73);for(int run=0;run<20;run++)inputs.add(IntStream.range(0,1+random.nextInt(50)).map(i->random.nextInt()).boxed().toList());for(List<Integer> input:inputs){var trace=algorithm.execute(input);assertThat(trace.summary().resultValues()).as(algorithm.id()).isEqualTo(input.stream().sorted().toList());assertThat(trace.summary().eventCount()).isEqualTo(trace.events().size()).isLessThanOrEqualTo(10_000);for(int i=0;i<trace.events().size();i++){var event=trace.events().get(i);assertThat(event.sequence()).isEqualTo(i+1);assertThat(event.pseudocodeLineId()).isNotBlank();assertThat(event.state()).hasSize(input.size());for(var range:event.sortedRanges()){assertThat(range.fromIndex()).isBetween(0,input.size()-1);assertThat(range.throughIndex()).isBetween(range.fromIndex(),input.size()-1);}}}}
 @Test void stableAlgorithmsKeepDuplicateIdentity(){for(var algorithm:List.of(new InsertionSortAlgorithm(),new BubbleSortAlgorithm(),new MergeSortAlgorithm())){var trace=algorithm.execute(List.of(2,1,2,1));assertThat(trace.events().getLast().state().stream().filter(i->i.value()==1).map(TraceItem::id)).containsExactly(1,3);}}
 @Test void selectionAvoidsFictitiousSwaps(){assertThat(new SelectionSortAlgorithm().execute(List.of(1,2,3)).summary().operationCounts().get("SWAP")).isZero();}
 @Test void bubbleExplainsEarlyExit(){assertThat(new BubbleSortAlgorithm().execute(List.of(1,2,3)).events()).anyMatch(e->e.type()==SemanticEventType.NO_SWAP_COMPLETE);}
 @Test void mergeTakesLeftEqualFirst(){assertThat(new MergeSortAlgorithm().execute(List.of(2,1,1)).events().getLast().state().stream().filter(i->i.value()==1).map(TraceItem::id)).containsExactly(1,2);}
}
