import type { AlgorithmEvent, MetricType, TraceItem } from './types'
export interface AlgorithmAdapter { id:string; title:string; intro:string; warning?:string; pseudocode:readonly {id:string;text:string}[]; complexity:readonly {label:string;value:string;explanation:string}[]; presets:readonly {label:string;values:readonly number[]}[]; metrics:MetricType[]; explain:(event:AlgorithmEvent)=>string; indices:(event:AlgorithmEvent)=>number[]; annotations:(event:AlgorithmEvent)=>string[] }
const presets=[{label:'Sorted',values:[1,2,3,4,5,6,7,8]},{label:'Reverse sorted',values:[8,7,6,5,4,3,2,1]},{label:'Duplicates',values:[5,3,5,2,3,1,5,2]},{label:'Negative values',values:[-3,7,-1,-8,4,0,-5]}] as const
const complexity=(best:string,average:string,worst:string,space:string)=>[{label:'Best',value:best,explanation:'Best-case running time.'},{label:'Average',value:average,explanation:'Typical running time.'},{label:'Worst',value:worst,explanation:'Worst-case running time.'},{label:'Space',value:space,explanation:'Additional working storage.'}]
const lines=(...ids:string[])=>ids.map(id=>({id,text:id.replaceAll('-',' ')}))
const values=(items?:TraceItem[])=>items?.map(item=>item.value).join(' and ') ?? ''
function genericExplain(e:AlgorithmEvent){switch(e.type){case'COMPARE':return `Compare ${values(e.data.items)}.`;case'READ':return `Read ${values(e.data.items)}.`;case'SWAP':return `Swap indices ${(e.data.indices??[]).join(' and ')}.`;case'WRITE':return `Write ${values(e.data.items)}.`;case'MARK_SORTED':return `Mark positions ${e.data.fromIndex} through ${e.data.throughIndex} sorted.`;case'MINIMUM_UPDATE':return `A new minimum, ${e.data.item?.value}, was found at index ${e.data.index}.`;case'PASS_START':return `Begin bubble pass ${e.data.pass}.`;case'PASS_COMPLETE':return `Pass ${e.data.pass} is complete; the sorted suffix has grown.`;case'NO_SWAP_COMPLETE':return 'No swaps occurred, so the entire array is sorted and execution stops early.';case'SPLIT_RANGE':return `Split range ${e.data.left}–${e.data.right} at ${e.data.middle}.`;case'BEGIN_MERGE':return `Begin merging the ranges around index ${e.data.middle}.`;case'BUFFER_MOVE':return `Move an item into the auxiliary buffer: ${values(e.data.buffer)}.`;case'COMPLETE_MERGE':return `Range ${e.data.left}–${e.data.right} is merged.`;case'PIVOT_SELECT':return `Choose the last item at index ${e.data.pivotIndex} as pivot.`;case'PARTITION_ACTIVE':return `Scan index ${e.data.scanner}; the partition boundary is ${e.data.boundary}.`;case'PARTITION_COMPLETE':return `The pivot is finalized at index ${e.data.pivotIndex}.`;case'BUILD_HEAP':return 'Build a max heap from the array, starting with the last parent.';case'ROOT_SELECT':return 'Select the heap root, which is the largest remaining value.';case'HEAPIFY':return `Restore the heap relationship from parent ${e.data.rootIndex}${e.data.childIndex!>=0?` toward child ${e.data.childIndex}`:''}.`;case'HEAP_SHRINK':return `Shrink the heap to ${e.data.heapSize} items and grow the sorted suffix.`;case'SELECT':return `Select ${e.data.item?.value} at index ${e.data.index}.`;default:return 'Advance the algorithm.'}}
const indices=(e:AlgorithmEvent)=>e.data.indices??(e.data.index!==undefined?[e.data.index]:e.data.scanner!==undefined?[e.data.scanner,e.data.boundary!,e.data.pivotIndex!].filter(Number.isInteger):e.data.rootIndex!==undefined?[e.data.rootIndex,e.data.childIndex!].filter(i=>i>=0):[])
const annotations=(e:AlgorithmEvent)=>e.type==='PIVOT_SELECT'?['pivot']:e.type==='PARTITION_ACTIVE'?['scanner','boundary','pivot']:e.type==='HEAPIFY'?['parent','child']:[]
const make=(id:string,title:string,pseudocode:string[],cost:string[],metrics:MetricType[],extra:Partial<AlgorithmAdapter>={}):AlgorithmAdapter=>({id,title,intro:`Explore how ${title.toLowerCase()} orders the same identifiable items step by step.`,pseudocode:lines(...pseudocode),complexity:complexity(cost[0],cost[1],cost[2],cost[3]),presets,metrics,explain:genericExplain,indices,annotations,...extra})
export const adapters:Record<string,AlgorithmAdapter>={
 insertion:make('insertion','Insertion Sort',['select-current','read-adjacent','compare-adjacent','swap-adjacent','write-swapped-values','move-left','complete-pass'],['O(n)','O(n²)','O(n²)','O(1)'],['COMPARISONS','READS','WRITES','SWAPS']),
 selection:make('selection','Selection Sort',['select-minimum','read-candidate','compare-candidate','update-minimum','place-minimum','write-placement','complete-position'],['O(n²)','O(n²)','O(n²)','O(1)'],['COMPARISONS','READS','WRITES','SWAPS']),
 bubble:make('bubble','Bubble Sort',['begin-pass','read-adjacent','compare-adjacent','swap-adjacent','write-swap','complete-pass','early-complete'],['O(n)','O(n²)','O(n²)','O(1)'],['COMPARISONS','READS','WRITES','SWAPS']),
 merge:make('merge','Merge Sort',['split-range','begin-merge','compare-halves','move-to-buffer','write-merged','complete-merge'],['O(n log n)','O(n log n)','O(n log n)','O(n)'],['COMPARISONS','WRITES']),
 quick:make('quick','Quick Sort',['select-pivot','scan-partition','compare-pivot','swap-partition','write-swap','partition-complete'],['O(n log n)','O(n log n)','O(n²)','O(log n)'],['COMPARISONS','WRITES','SWAPS'],{warning:'A deterministic last-element pivot makes sorted and reverse-sorted inputs degrade to quadratic time.'}),
 heap:make('heap','Heap Sort',['build-heap','select-root','heapify','compare-child','swap-heap','write-swap','shrink-heap','complete-heap'],['O(n log n)','O(n log n)','O(n log n)','O(1)'],['COMPARISONS','WRITES','SWAPS'])}
