import { useEffect,useMemo,useRef,useState } from 'react'
import { createAlgorithmTrace,createGraphTraversalTrace,fetchAlgorithmCatalog,TraceRequestError } from './api'
import { adapters } from './adapters'
import { ArrayVisualizer } from './components/ArrayVisualizer'
import { ComplexityPanel } from './components/ComplexityPanel'
import { GraphVisualizer } from './components/GraphVisualizer'
import { PlaybackControls } from './components/PlaybackControls'
import { PseudocodePanel } from './components/PseudocodePanel'
import { Timeline } from './components/Timeline'
import { parseIntegerList } from './input'
import { nextStep,previousStep } from './playback'
import type { AlgorithmCatalogEntry,AlgorithmTrace,GraphTraversalEvent,GraphTraversalTrace,MetricType,TraceItem,VisualizerTrace } from './types'
import './App.css'
const SAMPLE_INPUT='8, 3, 5, 1, 9, 6, 2, 7, 4'
type RequestState='empty'|'loading'|'ready'|'unavailable'
const metricEvent:Record<MetricType,string>={COMPARISONS:'COMPARE',READS:'READ',WRITES:'WRITE',SWAPS:'SWAP'}
const BFS_LINES=[{id:'bfs-initialize',text:'mark start discovered; enqueue start'},{id:'bfs-dequeue',text:'dequeue node; mark active; visit node'},{id:'bfs-complete-node',text:'mark node processed'},{id:'bfs-complete-traversal',text:'return traversal order'}]
function explainGraphEvent(event:GraphTraversalEvent){switch(event.type){case'TRAVERSAL_INITIALIZED':return `Discover and enqueue ${event.data.startNode}.`;case'NODE_DEQUEUED':return `Dequeue and visit ${event.data.node}.`;case'NODE_COMPLETED':return `Finish ${event.data.node}; it has no neighbors to examine.`;case'TRAVERSAL_COMPLETED':return `Traversal complete: ${event.data.traversalOrder.join(', ')}.`}}
function App(){
 const [input,setInput]=useState(SAMPLE_INPUT),[graphInput,setGraphInput]=useState('A'),[catalog,setCatalog]=useState<AlgorithmCatalogEntry[]>([]),[catalogError,setCatalogError]=useState(false)
 const [algorithmId,setAlgorithmId]=useState('insertion'),[trace,setTrace]=useState<VisualizerTrace|null>(null)
 const [step,setStep]=useState(-1),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(700),[requestState,setRequestState]=useState<RequestState>('empty'),[inputError,setInputError]=useState('')
 const abortRef=useRef<AbortController|null>(null),requestRef=useRef(0)
 const catalogEntry=catalog.find(entry=>entry.id===algorithmId),isGraph=catalogEntry?.family==='GRAPH_TRAVERSAL'||algorithmId==='bfs'
 const adapter=adapters[algorithmId]??adapters.insertion
 const graphTrace:GraphTraversalTrace|null=trace?.algorithm.family==='GRAPH_TRAVERSAL'?trace as GraphTraversalTrace:null
 const sortingTrace:AlgorithmTrace|null=trace?.algorithm.family==='SORTING'?trace as AlgorithmTrace:null
 const graphEvent=graphTrace&&step>=0?graphTrace.events[step]:undefined,sortingEvent=sortingTrace&&step>=0?sortingTrace.events[step]:undefined,event=graphEvent??sortingEvent,atStart=step<0,atEnd=!trace||step>=trace.events.length-1,completed=requestState==='ready'&&!!trace&&atEnd
 const counts=useMemo(()=>Object.fromEntries(adapter.metrics.map(metric=>[metric,(sortingTrace?.events.slice(0,step+1)??[]).filter(e=>e.type===metricEvent[metric]).length])),[adapter,step,sortingTrace])
 async function loadCatalog(){setCatalogError(false);try{const entries=await fetchAlgorithmCatalog();const supported=entries.filter(e=>e.contractVersion==='2.0'&&(e.family==='GRAPH_TRAVERSAL'||!!adapters[e.id]));setCatalog(supported);const requested=new URLSearchParams(location.search).get('algorithm')??'insertion';const selected=supported.some(e=>e.id===requested)?requested:supported[0]?.id;if(selected)setAlgorithmId(selected)}catch{setCatalogError(true)}}
 useEffect(()=>{fetchAlgorithmCatalog().then(entries=>{const supported=entries.filter(e=>e.contractVersion==='2.0'&&(e.family==='GRAPH_TRAVERSAL'||!!adapters[e.id]));setCatalog(supported);const requested=new URLSearchParams(location.search).get('algorithm')??'insertion';const selected=supported.some(e=>e.id===requested)?requested:supported[0]?.id;if(selected)setAlgorithmId(selected)}).catch(()=>setCatalogError(true))},[])
 useEffect(()=>{if(!playing||!trace||atEnd)return;const timer=setTimeout(()=>setStep(s=>nextStep(s,trace.events.length)),speed);return()=>clearTimeout(timer)},[playing,trace,atEnd,speed,step])
 function changeAlgorithm(id:string){abortRef.current?.abort();requestRef.current++;setAlgorithmId(id);setTrace(null);setStep(-1);setPlaying(false);setRequestState('empty');const url=new URL(location.href);url.searchParams.set('algorithm',id);history.replaceState(null,'',url)}
 async function visualize(source=isGraph?graphInput:input){let parsed:number[]|undefined;const node=source.trim();if(isGraph){if(!/^[A-Za-z0-9_-]{1,16}$/.test(node)){setInputError('Use one node label containing 1–16 letters, digits, underscores, or hyphens.');return}}else{parsed=parseIntegerList(source)??undefined;if(!parsed){setInputError('Use 1–50 signed 32-bit whole numbers separated by commas or spaces.');return}}abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;const request=++requestRef.current;setRequestState('loading');setInputError('');setTrace(null);setStep(-1);setPlaying(false);try{const result=isGraph?await createGraphTraversalTrace(node,controller.signal):await createAlgorithmTrace(algorithmId,parsed!,controller.signal);if(request===requestRef.current){setTrace(result);setRequestState('ready')}}catch(error){if(controller.signal.aborted||request!==requestRef.current)return;if(error instanceof TraceRequestError&&error.kind==='validation'){setInputError(error.message);setRequestState('empty')}else setRequestState('unavailable')}}
 const explanation=completed?(isGraph?'Breadth-first traversal is complete.':'Every value is now in ascending order.'):graphEvent?explainGraphEvent(graphEvent):sortingEvent?adapter.explain(sortingEvent):trace?'Start playback to inspect the trace.':'Build a trace to see why each step happens.'
 const buffer:TraceItem[]=sortingEvent&&'buffer' in sortingEvent.data?sortingEvent.data.buffer:[]
 const eventItems=sortingEvent?.state.items
 return <main><div className="sr-only" role="status" aria-live="polite">{requestState==='loading'?`Building ${isGraph?'Breadth-First Search':adapter.title} trace.`:catalogError?'The algorithm catalog is unavailable.':completed?(isGraph?'Traversal complete.':'Sorting complete.'):explanation}</div>
  <header className="masthead"><div className="eyebrow"><span/>Algorithm Visualization Workbench</div><h1>See the logic.<br/><em>Step by step.</em></h1><p>{isGraph?'Watch breadth-first search discover, visit, and finish nodes in queue order.':adapter.intro}</p></header>
  <section className="input-panel" aria-labelledby="input-title"><div><span className="section-number">01</span><h2 id="input-title">Choose and build</h2><p id="input-help">{isGraph?'Enter one node label.':'Enter whole numbers separated by commas or spaces.'}</p></div><div><label htmlFor="algorithm-select">Algorithm</label><select id="algorithm-select" value={algorithmId} disabled={catalogError||!catalog.length} onChange={e=>changeAlgorithm(e.target.value)}>{catalog.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
  {catalogError?<div className="state-panel unavailable-state" role="alert"><strong>Algorithms unavailable</strong><span>The executable algorithm catalog could not be loaded.</span><button className="button" onClick={()=>void loadCatalog()}>Retry catalog</button></div>:<>{isGraph?<><div className="input-row"><label className="sr-only" htmlFor="graph-input">Graph node</label><input id="graph-input" value={graphInput} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e=>setGraphInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void visualize()}/><button className="button button--run" disabled={requestState==='loading'} onClick={()=>void visualize()}>{requestState==='loading'?'Building…':'Visualize'}</button></div><div className="start-node"><label htmlFor="start-node">Start node</label><select id="start-node" value={/^[A-Za-z0-9_-]{1,16}$/.test(graphInput.trim())?graphInput.trim():''} onChange={()=>{}} disabled={!/^[A-Za-z0-9_-]{1,16}$/.test(graphInput.trim())}>{/^[A-Za-z0-9_-]{1,16}$/.test(graphInput.trim())&&<option>{graphInput.trim()}</option>}</select></div></>:<><div className="input-row"><label className="sr-only" htmlFor="array-input">Array values</label><input id="array-input" value={input} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void visualize()}/><button className="button button--run" disabled={requestState==='loading'} onClick={()=>void visualize()}>{requestState==='loading'?'Building…':'Visualize'}</button></div><div className="presets" aria-label="Preset arrays">{adapter.presets.map(p=><button key={p.label} onClick={()=>{const value=p.values.join(', ');setInput(value);void visualize(value)}}>{p.label}</button>)}</div></>}</>}
  {inputError&&<p className="error" role="alert">{inputError}</p>}</section>
  <section className="workbench" aria-labelledby="visualizer-title"><div className="workbench-header"><div><span className="section-number">02</span><h2 id="visualizer-title">{isGraph?'Breadth-First Search':adapter.title}</h2></div></div>{!isGraph&&adapter.warning&&<p className="algorithm-warning">{adapter.warning}</p>}<div className="visualizer-grid"><div>{requestState==='unavailable'?<div className="state-panel" role="alert"><strong>Visualizer unavailable</strong><button className="button" onClick={()=>void visualize()}>Retry</button></div>:graphTrace?<GraphVisualizer node={graphTrace.input.startNode} state={graphEvent?.state}/>:sortingTrace?<ArrayVisualizer items={eventItems??sortingTrace.input.values.map((value,id)=>({id,value}))} activeIndices={sortingEvent?adapter.indices(sortingEvent):[]} eventType={sortingEvent?.type} complete={completed} sortedRanges={sortingEvent?.state.sortedRanges??[]} annotations={sortingEvent?adapter.annotations(sortingEvent):[]} buffer={buffer}/>:<div className="state-panel"><strong>Ready when you are</strong></div>}</div><PseudocodePanel activeLineId={event?.pseudocodeLineId} lines={isGraph?BFS_LINES:adapter.pseudocode}/></div>
  <div className="status-row"><div className="step-status"><strong>{completed?'Complete':trace?`Step ${step+1} of ${trace.events.length}`:'Ready'}</strong><span>{explanation}</span></div>{graphTrace?<div className="metrics" aria-label="Traversal metrics"><div><strong>{graphTrace.result.visitedNodeCount}</strong><span>visited</span></div><div><strong>{graphTrace.result.edgeExaminationCount}</strong><span>edges examined</span></div><div><strong>{graphTrace.result.maximumQueueSize}</strong><span>max queue</span></div></div>:<div className="metrics" aria-label="Event counters">{adapter.metrics.map(m=><div key={m}><strong>{counts[m]??0}</strong><span>{m.toLowerCase()}</span></div>)}</div>}</div>
  <Timeline position={step+1} eventCount={trace?.events.length??0} disabled={requestState!=='ready'} onChange={p=>{setPlaying(false);setStep(p-1)}}/><PlaybackControls playing={playing&&!atEnd} atStart={atStart||requestState!=='ready'} atEnd={atEnd||requestState!=='ready'} speed={speed} onPlayPause={()=>setPlaying(v=>!v)} onPrevious={()=>{setPlaying(false);setStep(previousStep)}} onNext={()=>{setPlaying(false);setStep(s=>trace?nextStep(s,trace.events.length):s)}} onReset={()=>{setPlaying(false);setStep(-1)}} onSpeedChange={setSpeed}/><ComplexityPanel items={isGraph?[{label:'Time',value:'O(V + E)',explanation:'Each reachable node and edge is examined.'},{label:'Space',value:'O(V)',explanation:'The queue and node state grow with the graph.'}]:adapter.complexity}/></section><footer>Built for curiosity · Java 25 + Spring Boot + React</footer></main>
}
export default App
