import { useEffect, useMemo, useRef, useState } from 'react'
import { createAlgorithmTrace, createSearchTrace, createTreeTrace, fetchAlgorithmCatalog, TraceRequestError } from './api'
import { adapters } from './adapters'
import { ArrayVisualizer } from './components/ArrayVisualizer'
import { SearchVisualizer } from './components/SearchVisualizer'
import { ComplexityPanel } from './components/ComplexityPanel'
import { GraphVisualizer } from './components/GraphVisualizer'
import { TreeVisualizer } from './components/TreeVisualizer'
import { PlaybackControls } from './components/PlaybackControls'
import { PseudocodePanel } from './components/PseudocodePanel'
import { Timeline } from './components/Timeline'
import { parseGraphInput, parseIntegerList, validateGraphInput } from './input'
import { resolveAlgorithmAdapter } from './algorithmCapabilities'
import type { GraphPreset } from './graphPresets'
import type { SearchPreset } from './searchPresets'
import { searchPresets } from './searchPresets'
import { nextStep, previousStep } from './playback'
import type { AlgorithmCatalogEntry, AlgorithmTrace, GraphAlgorithmTrace, MetricType, SearchTrace, TreeOperation, TreeTrace, TraceItem, VisualizerTrace } from './types'
import './App.css'
const SAMPLE_INPUT = '8, 3, 5, 1, 9, 6, 2, 7, 4'
type RequestState = 'empty' | 'loading' | 'ready' | 'unavailable'
const metricEvent: Record<MetricType, string> = { COMPARISONS: 'COMPARE', READS: 'READ', WRITES: 'WRITE', SWAPS: 'SWAP' }
function App() {
  const [input, setInput] = useState(SAMPLE_INPUT), [searchInput, setSearchInput] = useState('8, 3, 5, 1'), [treeInput, setTreeInput] = useState('8, 3, 10, 1, 6'), [treeOperation, setTreeOperation] = useState<TreeOperation['kind']>('PREORDER'), [lookupTarget, setLookupTarget] = useState('5'), [searchTarget, setSearchTarget] = useState('5'), [graphInput, setGraphInput] = useState('A'), [selectedStart, setSelectedStart] = useState('A'), [selectedDestination, setSelectedDestination] = useState(''), [catalog, setCatalog] = useState<AlgorithmCatalogEntry[]>([]), [catalogError, setCatalogError] = useState(false)
  const [algorithmId, setAlgorithmId] = useState('insertion'), [trace, setTrace] = useState<VisualizerTrace | null>(null)
  const [step, setStep] = useState(-1), [playing, setPlaying] = useState(false), [speed, setSpeed] = useState(700), [requestState, setRequestState] = useState<RequestState>('empty'), [inputError, setInputError] = useState('')
  const abortRef = useRef<AbortController | null>(null), requestRef = useRef(0)
  const capability = useMemo(() => resolveAlgorithmAdapter(catalog.find(entry => entry.id === algorithmId)), [catalog, algorithmId])
  const graphAdapter = capability && (capability.family === 'GRAPH_TRAVERSAL' || capability.family === 'PATHFINDING') ? capability.adapter : undefined, treeAdapter = capability?.family === 'TREE' ? capability.adapter : undefined, isGraph = !!graphAdapter, isTree = !!treeAdapter, isSearch = capability?.family === 'SEARCH'
  const parsedGraph = useMemo(() => parseGraphInput(graphInput), [graphInput])
  const effectiveStart = parsedGraph?.nodes.includes(selectedStart) ? selectedStart : parsedGraph?.nodes[0] ?? ''
  const effectiveDestination = parsedGraph?.nodes.includes(selectedDestination) ? selectedDestination : ''
  const adapter = capability && (capability.family === 'SORTING' || capability.family === 'SEARCH') ? capability.adapter : adapters.insertion
  const learningAdapter = graphAdapter ?? treeAdapter ?? adapter
  const graphTrace: GraphAlgorithmTrace | null = trace && (trace.algorithm.family === 'GRAPH_TRAVERSAL' || trace.algorithm.family === 'PATHFINDING') ? trace as GraphAlgorithmTrace : null
  const sortingTrace: AlgorithmTrace | null = trace?.algorithm.family === 'SORTING' ? trace as AlgorithmTrace : null
  const searchTrace: SearchTrace | null = trace?.algorithm.family === 'SEARCH' ? trace as SearchTrace : null
  const treeTrace: TreeTrace | null = trace?.algorithm.family === 'TREE' ? trace as TreeTrace : null
  const graphEvent = graphTrace && step >= 0 ? graphTrace.events[step] : undefined, sortingEvent = sortingTrace && step >= 0 ? sortingTrace.events[step] : undefined, searchEvent = searchTrace && step >= 0 ? searchTrace.events[step] : undefined, treeEvent = treeTrace && step >= 0 ? treeTrace.events[step] : undefined, event = graphEvent ?? sortingEvent ?? searchEvent ?? treeEvent, atStart = step < 0, atEnd = !trace || step >= trace.events.length - 1, completed = requestState === 'ready' && !!trace && atEnd
  const counts = useMemo(() => Object.fromEntries(adapter.metrics.map(metric => [metric, (sortingTrace?.events.slice(0, step + 1) ?? []).filter(e => e.type === metricEvent[metric]).length])), [adapter.metrics, step, sortingTrace])
  async function loadCatalog() { setCatalogError(false); try { const entries = await fetchAlgorithmCatalog(); const supported = entries.filter(e => resolveAlgorithmAdapter(e)); setCatalog(supported); const requested = new URLSearchParams(location.search).get('algorithm') ?? 'insertion'; const selected = supported.some(e => e.id === requested) ? requested : supported[0]?.id; if (selected) setAlgorithmId(selected) } catch { setCatalogError(true) } }
  useEffect(() => { fetchAlgorithmCatalog().then(entries => { const supported = entries.filter(e => resolveAlgorithmAdapter(e)); setCatalog(supported); const requested = new URLSearchParams(location.search).get('algorithm') ?? 'insertion'; const selected = supported.some(e => e.id === requested) ? requested : supported[0]?.id; if (selected) setAlgorithmId(selected) }).catch(() => setCatalogError(true)) }, [])
  useEffect(() => { if (!playing || !trace || atEnd) return; const timer = setTimeout(() => setStep(s => nextStep(s, trace.events.length)), speed); return () => clearTimeout(timer) }, [playing, trace, atEnd, speed, step])
  function clearRun() { abortRef.current?.abort(); requestRef.current++; setTrace(null); setStep(-1); setPlaying(false); setRequestState('empty'); setInputError('') }
  function changeAlgorithm(id: string) { clearRun(); setAlgorithmId(id); const url = new URL(location.href); url.searchParams.set('algorithm', id); history.replaceState(null, '', url) }
  function changeGraphInput(value: string) { const graph = parseGraphInput(value); setGraphInput(value); setSelectedStart(current => graph?.nodes.includes(current) ? current : graph?.nodes[0] ?? ''); setSelectedDestination(current => graph?.nodes.includes(current) ? current : '') }
  function applyGraphPreset(preset: GraphPreset) { clearRun(); setGraphInput(preset.input); setSelectedStart(preset.startNode); setSelectedDestination(preset.destination ?? '') }
  function applySearchPreset(preset: SearchPreset) { clearRun(); setSearchInput(preset.values.join(', ')); setSearchTarget(String(preset.target)) }
  async function visualize(source = isGraph ? graphInput : isTree ? treeInput : isSearch ? searchInput : input) { let parsed: number[] | undefined; const validation = isGraph ? validateGraphInput(source) : null; const graph = validation?.graph ?? null; const treeTarget = Number(lookupTarget); const operation: TreeOperation = treeOperation === 'LOOKUP' ? { kind: 'LOOKUP', target: treeTarget } : { kind: 'PREORDER' }; if (isGraph) { if (!graph || !effectiveStart) { setInputError(validation?.error ?? 'Select a valid start node.'); return } if (graphAdapter!.destination === 'REQUIRED' && !effectiveDestination) { setInputError('Select a destination node.'); return } } else { parsed = parseIntegerList(source) ?? (isSearch && !source.trim() ? [] : undefined); const target = Number(searchTarget); if (!parsed || (isTree && (parsed.length > 31 || new Set(parsed).size !== parsed.length || (treeOperation === 'LOOKUP' && (!lookupTarget.trim() || !Number.isInteger(treeTarget) || treeTarget < -2147483648 || treeTarget > 2147483647)))) || (isSearch && (!searchTarget.trim() || !Number.isInteger(target) || target < -2147483648 || target > 2147483647))) { setInputError(isTree ? treeOperation === 'LOOKUP' ? 'Use 1–31 unique signed 32-bit whole numbers and a signed 32-bit lookup target.' : 'Use 1–31 unique signed 32-bit whole numbers separated by commas or spaces.' : isSearch ? 'Use signed 32-bit whole numbers and a whole-number target.' : 'Use 1–50 signed 32-bit whole numbers separated by commas or spaces.'); return } } abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const request = ++requestRef.current; setRequestState('loading'); setInputError(''); setTrace(null); setStep(-1); setPlaying(false); try { const result = isGraph ? await graphAdapter!.createTrace({ ...graph!, startNode: effectiveStart, ...(graphAdapter!.destination !== 'NONE' && effectiveDestination ? { destination: effectiveDestination } : {}) }, controller.signal) : isTree ? await createTreeTrace(parsed!, operation, controller.signal) : isSearch ? await createSearchTrace(algorithmId as 'linear-search' | 'binary-search', parsed!, Number(searchTarget), controller.signal) : await createAlgorithmTrace(algorithmId, parsed!, controller.signal); if (request === requestRef.current) { setTrace(result); setRequestState('ready') } } catch (error) { if (controller.signal.aborted || request !== requestRef.current) return; if (error instanceof TraceRequestError && error.kind === 'validation') { setInputError(error.message); setRequestState('empty') } else setRequestState('unavailable') } }
  const searchExplanation = searchEvent?.type === 'SEARCH_INITIALIZED' ? searchTrace?.algorithm.id === 'binary-search' ? 'Start with the inclusive interval covering every index.' : 'Start at index 0 and inspect values from left to right.' : searchEvent?.type === 'CANDIDATE_SELECTED' ? `Select ${searchEvent.data.value} at index ${searchEvent.data.index}.` : searchEvent?.type === 'TARGET_COMPARED' ? `${searchEvent.data.value} ${searchEvent.data.found ? 'equals' : searchEvent.data.relation === 'LESS' ? 'is less than' : 'is greater than'} target ${searchTrace?.input.target}.` : searchEvent?.type === 'SEARCH_INTERVAL_NARROWED' ? `Narrow the inclusive interval to indices ${searchEvent.data.lowerBound} through ${searchEvent.data.upperBound}.` : searchEvent?.type === 'SEARCH_FOUND' ? `Found ${searchEvent.data.value} at index ${searchEvent.data.index}.` : searchEvent?.type === 'SEARCH_NOT_FOUND' ? `${searchTrace?.input.target} was not found${searchTrace?.algorithm.id === 'binary-search' ? ' after the interval became empty' : ' after inspecting every value'}.` : ''
  const explanation = completed ? (isGraph ? graphTrace ? graphAdapter!.complete(graphTrace.result) : '' : treeTrace ? treeTrace.result.kind === 'LOOKUP' ? treeTrace.result.found ? `Found ${treeTrace.result.target} after inspecting ${treeTrace.result.visitedValues.join(' → ')}.` : `${treeTrace.result.target} was not found after inspecting ${treeTrace.result.visitedValues.join(' → ')}.` : `Preorder traversal complete: ${treeTrace.result.visitedValues.join(' → ')}.` : searchTrace ? searchTrace.result.found ? `Found ${searchTrace.input.target} at index ${searchTrace.result.foundIndex}.` : `${searchTrace.input.target} was not found.` : 'Every value is now in ascending order.') : graphEvent ? graphAdapter!.explain(graphEvent) : treeEvent ? treeAdapter!.explain(treeEvent) : sortingEvent ? adapter.explain(sortingEvent) : searchEvent ? searchExplanation : trace ? 'Start playback to inspect the trace.' : 'Build a trace to see why each step happens.'
  const buffer: TraceItem[] = sortingEvent && 'buffer' in sortingEvent.data ? sortingEvent.data.buffer : []
  const eventItems = sortingEvent?.state.items
  const graphWarning = graphAdapter?.inputWarning([...(graphTrace?.input.edges ?? []), ...(parsedGraph?.edges ?? [])])
  const completionAnnouncement = graphAdapter
    ? graphAdapter.completionAnnouncement
    : searchTrace
      ? searchTrace.result.found
        ? `Search found ${searchTrace.input.target} at index ${searchTrace.result.foundIndex}.`
        : `Search did not find ${searchTrace.input.target}.`
      : treeTrace ? treeTrace.result.kind === 'LOOKUP'
        ? treeTrace.result.found
          ? `Lookup found ${treeTrace.result.target} after inspecting ${treeTrace.result.visitedValues.join(', ')}.`
          : `Lookup did not find ${treeTrace.result.target} after inspecting ${treeTrace.result.visitedValues.join(', ')}.`
        : 'Preorder traversal complete.' : 'Sorting complete.'
  return <main><div className="sr-only" role="status" aria-live="polite">{requestState === 'loading' ? `Building ${learningAdapter.title} trace.` : catalogError ? 'The algorithm catalog is unavailable.' : completed ? completionAnnouncement : explanation}</div>
    <header className="masthead"><div className="eyebrow"><span />Algorithm Visualization Workbench</div><h1>See the logic.<br /><em>Step by step.</em></h1><p>{learningAdapter.intro}</p></header>
    <section className="input-panel" aria-labelledby="input-title"><div><span className="section-number">01</span><h2 id="input-title">Choose and build</h2><p id="input-help">{isGraph ? 'Enter standalone nodes or undirected edges, one per line. Add an optional weight from 1–99, for example A-B:7.' : isTree ? 'Enter 1–31 unique signed 32-bit whole numbers to form a binary search tree.' : isSearch ? 'Enter up to 50 whole numbers and a target value.' : 'Enter whole numbers separated by commas or spaces.'}</p></div><div><label htmlFor="algorithm-select">Algorithm</label><select id="algorithm-select" value={algorithmId} disabled={catalogError || !catalog.length} onChange={e => changeAlgorithm(e.target.value)}>{catalog.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
      {catalogError ? <div className="state-panel unavailable-state" role="alert"><strong>Algorithms unavailable</strong><span>The executable algorithm catalog could not be loaded.</span><button className="button" onClick={() => void loadCatalog()}>Retry catalog</button></div> : isTree ? <div className="input-row"><label className="sr-only" htmlFor="tree-input">BST insertion sequence</label><input id="tree-input" value={treeInput} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e => setTreeInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && void visualize()} /><label htmlFor="tree-operation">Tree operation</label><select id="tree-operation" value={treeOperation} onChange={e => setTreeOperation(e.target.value as TreeOperation['kind'])}><option value="PREORDER">Preorder</option><option value="LOOKUP">Lookup</option></select>{treeOperation === 'LOOKUP' && <><label className="sr-only" htmlFor="lookup-target">Lookup target</label><input id="lookup-target" value={lookupTarget} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e => setLookupTarget(e.target.value)} onKeyDown={e => e.key === 'Enter' && void visualize()} /></>}<button className="button button--run" disabled={requestState === 'loading'} onClick={() => void visualize()}>{requestState === 'loading' ? 'Building…' : `Visualize ${treeOperation.toLowerCase()}`}</button></div> : isSearch ? <div className="input-row"><label className="sr-only" htmlFor="search-input">Search values</label><input id="search-input" value={searchInput} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e => setSearchInput(e.target.value)} /><label className="sr-only" htmlFor="search-target">Target</label><input id="search-target" value={searchTarget} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e => setSearchTarget(e.target.value)} /><button className="button button--run" disabled={requestState === 'loading'} onClick={() => void visualize()}>{requestState === 'loading' ? 'Building…' : 'Visualize'}</button></div> : isGraph ? <div className="input-row"><label className="sr-only" htmlFor="graph-input">Graph input</label><textarea id="graph-input" value={graphInput} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e => changeGraphInput(e.target.value)} /><button className="button button--run" disabled={requestState === 'loading'} onClick={() => void visualize()}>{requestState === 'loading' ? 'Building…' : 'Visualize'}</button></div> : <div className="input-row"><label className="sr-only" htmlFor="array-input">Array values</label><input id="array-input" value={input} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && void visualize()} /><button className="button button--run" disabled={requestState === 'loading'} onClick={() => void visualize()}>{requestState === 'loading' ? 'Building…' : 'Visualize'}</button></div>}
      {isSearch && <div className="presets" aria-label="Preset searches">{searchPresets.map(p => <button key={p.label} title={p.description} onClick={() => applySearchPreset(p)}>{p.label}</button>)}</div>}
      {isGraph && <><div className="presets" aria-label="Preset graphs">{graphAdapter!.presets.map(p => <button key={p.label} title={p.description} onClick={() => applyGraphPreset(p)}>{p.label}</button>)}</div><div className="start-node"><label htmlFor="start-node">Start node</label><select id="start-node" value={effectiveStart} onChange={e => setSelectedStart(e.target.value)} disabled={!parsedGraph}>{parsedGraph?.nodes.map(node => <option key={node}>{node}</option>)}</select></div>{graphAdapter!.destination !== 'NONE' && <div className="start-node"><label htmlFor="destination-node">Destination</label><select id="destination-node" value={effectiveDestination} onChange={e => setSelectedDestination(e.target.value)} disabled={!parsedGraph}><option value="">{graphAdapter!.destination === 'REQUIRED' ? 'Select destination' : 'No destination'}</option>{parsedGraph?.nodes.map(node => <option key={node}>{node}</option>)}</select></div>}</>}
      {inputError && <p className="error" role="alert">{inputError}</p>}</section>
    <section className="workbench" aria-labelledby="visualizer-title"><div className="workbench-header"><div><span className="section-number">02</span><h2 id="visualizer-title">{learningAdapter.title}</h2></div></div>{graphAdapter && <p className="algorithm-guide">{graphAdapter.guide}</p>}{graphWarning && <p className="algorithm-warning">{graphWarning}</p>}{learningAdapter.warning && <p className="algorithm-warning">{learningAdapter.warning}</p>}<div className="visualizer-grid"><div>{requestState === 'unavailable' ? <div className="state-panel" role="alert"><strong>Visualizer unavailable</strong><button className="button" onClick={() => void visualize()}>Retry</button></div> : treeTrace ? <TreeVisualizer state={treeEvent?.state} /> : graphTrace ? <GraphVisualizer nodes={graphTrace.input.nodes} edges={graphTrace.input.edges} presentation={graphAdapter!.present(graphTrace.input.nodes, graphEvent?.state, completed ? graphTrace.result : undefined)} /> : searchTrace ? <SearchVisualizer values={searchTrace.input.values} target={searchTrace.input.target} selectedIndex={searchEvent?.state.selectedIndex} inspectedIndices={searchEvent?.state.inspectedIndices ?? []} foundIndex={completed && searchTrace.result.found ? searchTrace.result.foundIndex : undefined} lowerBound={searchEvent?.state.lowerBound} upperBound={searchEvent?.state.upperBound} /> : sortingTrace ? <ArrayVisualizer items={eventItems ?? sortingTrace.input.values.map((value, id) => ({ id, value }))} activeIndices={sortingEvent ? adapter.indices(sortingEvent) : []} eventType={sortingEvent?.type} complete={completed} sortedRanges={sortingEvent?.state.sortedRanges ?? []} annotations={sortingEvent ? adapter.annotations(sortingEvent) : []} buffer={buffer} /> : <div className="state-panel"><strong>Ready when you are</strong></div>}</div><PseudocodePanel activeLineId={event?.pseudocodeLineId} lines={learningAdapter.pseudocode} /></div>
      <div className="status-row"><div className="step-status"><strong>{completed ? 'Complete' : trace ? `Step ${step + 1} of ${trace.events.length}` : 'Ready'}</strong><span>{explanation}</span></div>{treeTrace ? <div className="metrics" aria-label="Tree metrics"><div><strong>{treeTrace.result.visitedNodeCount}</strong><span>visited</span></div><div><strong>{treeTrace.result.kind === 'LOOKUP' ? treeTrace.result.comparisonCount : treeTrace.result.constructionComparisonCount}</strong><span>{treeTrace.result.kind === 'LOOKUP' ? 'lookup comparisons' : 'construction comparisons'}</span></div></div> : graphTrace ? <div className="metrics" aria-label={graphAdapter!.metricsLabel}>{graphAdapter!.metrics(graphTrace.result).map(metric => <div key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span></div>)}</div> : searchTrace ? <div className="metrics" aria-label="Search metrics"><div><strong>{searchTrace.result.comparisons}</strong><span>comparisons</span></div></div> : <div className="metrics" aria-label="Event counters">{adapter.metrics.map(m => <div key={m}><strong>{counts[m] ?? 0}</strong><span>{m.toLowerCase()}</span></div>)}</div>}</div>
      <Timeline position={step + 1} eventCount={trace?.events.length ?? 0} disabled={requestState !== 'ready'} onChange={p => { setPlaying(false); setStep(p - 1) }} /><PlaybackControls playing={playing && !atEnd} atStart={atStart || requestState !== 'ready'} atEnd={atEnd || requestState !== 'ready'} speed={speed} onPlayPause={() => setPlaying(v => !v)} onPrevious={() => { setPlaying(false); setStep(previousStep) }} onNext={() => { setPlaying(false); setStep(s => trace ? nextStep(s, trace.events.length) : s) }} onReset={() => { setPlaying(false); setStep(-1) }} onSpeedChange={setSpeed} /><ComplexityPanel items={learningAdapter.complexity} /></section><footer>Built for curiosity · Java 25 + Spring Boot + React</footer></main>
}
export default App
