import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import App from './App'
const catalog=[{id:'insertion',name:'Insertion Sort',available:true,contractVersion:'1.0',inputConstraints:{maxInputItems:50,maxEvents:10000},metricTypes:['COMPARISONS']},{id:'selection',name:'Selection Sort',available:true,contractVersion:'1.0',inputConstraints:{maxInputItems:50,maxEvents:10000},metricTypes:['COMPARISONS']},{id:'future',name:'Future Sort',available:true,contractVersion:'2.0',inputConstraints:{maxInputItems:50,maxEvents:10000},metricTypes:[]}]
const trace={apiVersion:'1.0',algorithm:{id:'insertion',name:'Insertion Sort'},inputValues:[2,1],summary:{resultValues:[1,2],eventCount:1,operationCounts:{MARK_SORTED:1}},limits:{maxInputItems:50,maxEvents:10000},events:[{sequence:1,type:'MARK_SORTED',pseudocodeLineId:'complete-pass',state:[{id:1,value:1},{id:0,value:2}],sortedRanges:[{fromIndex:0,throughIndex:1}],data:{fromIndex:0,throughIndex:1}}]}
beforeEach(()=>{history.replaceState(null,'','/');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>new Response(JSON.stringify(String(input).endsWith('/api/v1/algorithms')?catalog:trace),{status:200,headers:{'Content-Type':'application/json'}})))})
afterEach(()=>vi.unstubAllGlobals())
describe('App algorithm workbench',()=>{
 it('loads compatible algorithms and reports hidden contracts',async()=>{render(<App/>);expect(await screen.findByRole('option',{name:'Insertion Sort'})).toBeInTheDocument();expect(screen.getByRole('option',{name:'Selection Sort'})).toBeInTheDocument();expect(screen.queryByRole('option',{name:'Future Sort'})).not.toBeInTheDocument();expect(screen.getByText(/hidden because/)).toBeInTheDocument()})
 it('preserves input, clears trace, updates URL, and waits on selection',async()=>{const user=userEvent.setup();render(<App/>);await screen.findByRole('option',{name:'Selection Sort'});const input=screen.getByLabelText('Array values');await user.clear(input);await user.type(input,'9, 4');await user.click(screen.getByRole('button',{name:'Visualize'}));await screen.findByRole('img');await user.selectOptions(screen.getByLabelText('Algorithm'),'selection');expect(input).toHaveValue('9, 4');expect(screen.queryByRole('img')).not.toBeInTheDocument();expect(location.search).toBe('?algorithm=selection');expect(fetch).toHaveBeenCalledTimes(2)})
 it('executes only on request and supports navigation',async()=>{const user=userEvent.setup();render(<App/>);await screen.findByRole('option',{name:'Insertion Sort'});expect(fetch).toHaveBeenCalledTimes(1);await user.click(screen.getByRole('button',{name:'Visualize'}));await screen.findByRole('img');expect(fetch).toHaveBeenCalledTimes(2);await user.click(screen.getByRole('button',{name:'Next step'}));expect(screen.getByText('Complete')).toBeInTheDocument()})
 it('shows retry when catalog fails',async()=>{vi.mocked(fetch).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(new Response(JSON.stringify(catalog),{status:200}));const user=userEvent.setup();render(<App/>);expect(await screen.findByText('Algorithms unavailable')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Retry catalog'}));await waitFor(()=>expect(screen.getByRole('option',{name:'Insertion Sort'})).toBeInTheDocument())})
})
