import { useEffect,useMemo,useRef,useState } from 'react'
import { createAlgorithmTrace,fetchAlgorithmCatalog,TraceRequestError } from './api'
import { adapters } from './adapters'
import { ArrayVisualizer } from './components/ArrayVisualizer'
import { ComplexityPanel } from './components/ComplexityPanel'
import { PlaybackControls } from './components/PlaybackControls'
import { PseudocodePanel } from './components/PseudocodePanel'
import { Timeline } from './components/Timeline'
import { parseIntegerList } from './input'
import { nextStep,previousStep } from './playback'
import type { AlgorithmCatalogEntry,AlgorithmTrace,MetricType,TraceItem } from './types'
import './App.css'
const SAMPLE_INPUT='8, 3, 5, 1, 9, 6, 2, 7, 4'
type RequestState='empty'|'loading'|'ready'|'unavailable'
const metricEvent:Record<MetricType,string>={COMPARISONS:'COMPARE',READS:'READ',WRITES:'WRITE',SWAPS:'SWAP'}
function App(){
 const [input,setInput]=useState(SAMPLE_INPUT),[catalog,setCatalog]=useState<AlgorithmCatalogEntry[]>([]),[catalogError,setCatalogError]=useState(false)
 const [algorithmId,setAlgorithmId]=useState('insertion'),[compatibility,setCompatibility]=useState(''),[trace,setTrace]=useState<AlgorithmTrace|null>(null)
 const [step,setStep]=useState(-1),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(700),[requestState,setRequestState]=useState<RequestState>('empty'),[inputError,setInputError]=useState('')
 const abortRef=useRef<AbortController|null>(null),requestRef=useRef(0)
 const adapter=adapters[algorithmId]??adapters.insertion,event=trace&&step>=0?trace.events[step]:undefined,atStart=step<0,atEnd=!trace||step>=trace.events.length-1,completed=requestState==='ready'&&!!trace&&atEnd
 const counts=useMemo(()=>Object.fromEntries(adapter.metrics.map(metric=>[metric,(trace?.events.slice(0,step+1)??[]).filter(e=>e.type===metricEvent[metric]).length])),[adapter,step,trace])
 async function loadCatalog(){setCatalogError(false);try{const entries=await fetchAlgorithmCatalog();const supported=entries.filter(e=>e.available&&e.contractVersion==='1.0'&&adapters[e.id]);const hidden=entries.length-supported.length;setCatalog(supported);setCompatibility(hidden?`${hidden} catalog ${hidden===1?'entry is':'entries are'} hidden because this frontend cannot render the contract.`:'');const requested=new URLSearchParams(location.search).get('algorithm')??'insertion';const selected=supported.some(e=>e.id===requested)?requested:supported[0]?.id;if(selected){setAlgorithmId(selected);if(selected!==requested)setCompatibility(message=>`${message} ${requested} is unavailable; selected ${selected}.`.trim());}}catch{setCatalogError(true)}}
 useEffect(()=>{fetchAlgorithmCatalog().then(entries=>{const supported=entries.filter(e=>e.available&&e.contractVersion==='1.0'&&adapters[e.id]);const hidden=entries.length-supported.length;setCatalog(supported);setCompatibility(hidden?`${hidden} catalog ${hidden===1?'entry is':'entries are'} hidden because this frontend cannot render the contract.`:'');const requested=new URLSearchParams(location.search).get('algorithm')??'insertion';const selected=supported.some(e=>e.id===requested)?requested:supported[0]?.id;if(selected)setAlgorithmId(selected)}).catch(()=>setCatalogError(true))},[])
 useEffect(()=>{if(!playing||!trace||atEnd)return;const timer=setTimeout(()=>setStep(s=>nextStep(s,trace.events.length)),speed);return()=>clearTimeout(timer)},[playing,trace,atEnd,speed,step])
 function changeAlgorithm(id:string){abortRef.current?.abort();requestRef.current++;setAlgorithmId(id);setTrace(null);setStep(-1);setPlaying(false);setRequestState('empty');const url=new URL(location.href);url.searchParams.set('algorithm',id);history.replaceState(null,'',url)}
 async function visualize(source=input){const parsed=parseIntegerList(source);if(!parsed){setInputError('Use 1–50 signed 32-bit whole numbers separated by commas or spaces.');return}abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;const request=++requestRef.current;setRequestState('loading');setInputError('');setTrace(null);setStep(-1);setPlaying(false);try{const result=await createAlgorithmTrace(algorithmId,parsed,controller.signal);if(request===requestRef.current){setTrace(result);setRequestState('ready')}}catch(error){if(controller.signal.aborted||request!==requestRef.current)return;if(error instanceof TraceRequestError&&error.kind==='validation'){setInputError(error.message);setRequestState('empty')}else setRequestState('unavailable')}}
 const explanation=completed?'Every value is now in ascending order.':event?adapter.explain(event):trace?'Start playback to inspect the trace.':'Build a trace to see why each step happens.'
 const buffer:TraceItem[]=event?.data.buffer??[]
 const eventItems=event?.state.map((item,id)=>typeof item==='number'?{id,value:item}:item)
 return <main><div className="sr-only" role="status" aria-live="polite">{requestState==='loading'?`Building ${adapter.title} trace.`:catalogError?'The algorithm catalog is unavailable.':completed?'Sorting complete.':explanation}</div>
  <header className="masthead"><div className="eyebrow"><span/>Algorithm Visualization Workbench</div><h1>See the logic.<br/><em>Step by step.</em></h1><p>{adapter.intro}</p></header>
  <section className="input-panel" aria-labelledby="input-title"><div><span className="section-number">01</span><h2 id="input-title">Choose and build</h2><p id="input-help">Enter whole numbers separated by commas or spaces.</p></div><div><label htmlFor="algorithm-select">Algorithm</label><select id="algorithm-select" value={algorithmId} disabled={catalogError||!catalog.length} onChange={e=>changeAlgorithm(e.target.value)}>{catalog.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
  {catalogError?<div className="state-panel unavailable-state" role="alert"><strong>Algorithms unavailable</strong><span>The executable algorithm catalog could not be loaded.</span><button className="button" onClick={()=>void loadCatalog()}>Retry catalog</button></div>:<><div className="input-row"><label className="sr-only" htmlFor="array-input">Array values</label><input id="array-input" value={input} aria-describedby="input-help" aria-invalid={!!inputError} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void visualize()}/><button className="button button--run" disabled={requestState==='loading'} onClick={()=>void visualize()}>{requestState==='loading'?'Building…':'Visualize'}</button></div><div className="presets" aria-label="Preset arrays">{adapter.presets.map(p=><button key={p.label} onClick={()=>{const value=p.values.join(', ');setInput(value);void visualize(value)}}>{p.label}</button>)}</div></>}
  {compatibility&&<p className="compatibility" role="status">{compatibility}</p>}{inputError&&<p className="error" role="alert">{inputError}</p>}</section>
  <section className="workbench" aria-labelledby="visualizer-title"><div className="workbench-header"><div><span className="section-number">02</span><h2 id="visualizer-title">{adapter.title}</h2></div></div>{adapter.warning&&<p className="algorithm-warning">{adapter.warning}</p>}<div className="visualizer-grid"><div>{requestState==='unavailable'?<div className="state-panel" role="alert"><strong>Visualizer unavailable</strong><button className="button" onClick={()=>void visualize()}>Retry</button></div>:trace?<ArrayVisualizer items={eventItems??trace.inputValues.map((value,id)=>({id,value}))} activeIndices={event?adapter.indices(event):[]} eventType={event?.type} complete={completed} sortedRanges={event?.sortedRanges??[]} annotations={event?adapter.annotations(event):[]} buffer={buffer}/>:<div className="state-panel"><strong>Ready when you are</strong></div>}</div><PseudocodePanel activeLineId={event?.pseudocodeLineId} lines={adapter.pseudocode}/></div>
  <div className="status-row"><div className="step-status"><strong>{completed?'Complete':trace?`Step ${step+1} of ${trace.events.length}`:'Ready'}</strong><span>{explanation}</span></div><div className="metrics" aria-label="Event counters">{adapter.metrics.map(m=><div key={m}><strong>{counts[m]??0}</strong><span>{m.toLowerCase()}</span></div>)}</div></div>
  <Timeline position={step+1} eventCount={trace?.events.length??0} disabled={requestState!=='ready'} onChange={p=>{setPlaying(false);setStep(p-1)}}/><PlaybackControls playing={playing&&!atEnd} atStart={atStart||requestState!=='ready'} atEnd={atEnd||requestState!=='ready'} speed={speed} onPlayPause={()=>setPlaying(v=>!v)} onPrevious={()=>{setPlaying(false);setStep(previousStep)}} onNext={()=>{setPlaying(false);setStep(s=>trace?nextStep(s,trace.events.length):s)}} onReset={()=>{setPlaying(false);setStep(-1)}} onSpeedChange={setSpeed}/><ComplexityPanel items={adapter.complexity}/></section><footer>Built for curiosity · Java 25 + Spring Boot + React</footer></main>
}
export default App
