import { fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import App from './App'
const constraints={kind:'SORTING',minimumValues:1,maximumValues:50,minimumValue:-2147483648,maximumValue:2147483647}
const catalog=[{id:'insertion',name:'Insertion Sort',family:'SORTING',contractVersion:'2.0',constraints}]
const trace={apiVersion:'2.0',algorithm:{id:'insertion',name:'Insertion Sort',family:'SORTING'},input:{kind:'SORTING',values:[2,1]},result:{kind:'SORTING',values:[1,2]},limits:{maximumEvents:10000},events:[{sequence:1,type:'MARK_SORTED',pseudocodeLineId:'complete-pass',state:{kind:'SORTING',items:[{id:1,value:1},{id:0,value:2}],sortedRanges:[{fromIndex:0,throughIndex:1}]},data:{kind:'MARK_SORTED',fromIndex:0,throughIndex:1}}]}
beforeEach(()=>{history.replaceState(null,'','/');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>new Response(JSON.stringify(String(input).endsWith('/api/v2/algorithms')?catalog:trace),{status:200,headers:{'Content-Type':'application/json'}})))})
afterEach(()=>vi.unstubAllGlobals())
describe('App algorithm workbench',()=>{
 it('loads the v2 insertion algorithm',async()=>{render(<App/>);expect(await screen.findByRole('option',{name:'Insertion Sort'})).toBeInTheDocument()})
 it('keeps the input unchanged while building a trace',async()=>{const user=userEvent.setup();render(<App/>);await screen.findByRole('option',{name:'Insertion Sort'});const input=screen.getByLabelText('Array values');await user.clear(input);await user.type(input,'9, 4');await user.click(screen.getByRole('button',{name:'Visualize'}));await screen.findByRole('img');expect(input).toHaveValue('9, 4');expect(fetch).toHaveBeenCalledTimes(2)})
 it('executes only on request and supports navigation',async()=>{const user=userEvent.setup();render(<App/>);await screen.findByRole('option',{name:'Insertion Sort'});expect(fetch).toHaveBeenCalledTimes(1);await user.click(screen.getByRole('button',{name:'Visualize'}));await screen.findByRole('img');expect(fetch).toHaveBeenCalledTimes(2);await user.click(screen.getByRole('button',{name:'Next step'}));expect(screen.getByText('Complete')).toBeInTheDocument()})
 it('shows retry when catalog fails',async()=>{vi.mocked(fetch).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(new Response(JSON.stringify(catalog),{status:200}));const user=userEvent.setup();render(<App/>);expect(await screen.findByText('Algorithms unavailable')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Retry catalog'}));await waitFor(()=>expect(screen.getByRole('option',{name:'Insertion Sort'})).toBeInTheDocument())})
 it('runs and plays the single-node BFS trace',async()=>{const graphCatalog={id:'bfs',name:'Breadth-First Search',family:'GRAPH_TRAVERSAL',contractVersion:'2.0',constraints:{kind:'GRAPH_TRAVERSAL',minimumNodes:1,maximumNodes:12,maximumEdges:66,nodeLabelPattern:'^[A-Za-z0-9_-]{1,16}$',directed:false,weighted:false}};const graphTrace={apiVersion:'2.0',algorithm:{id:'bfs',name:'Breadth-First Search',family:'GRAPH_TRAVERSAL'},input:{kind:'GRAPH_TRAVERSAL',nodes:['A'],edges:[],startNode:'A'},result:{kind:'GRAPH_TRAVERSAL',traversalOrder:['A'],parents:{},unreachableNodes:[],visitedNodeCount:1,edgeExaminationCount:0,maximumQueueSize:1},limits:{maximumEvents:10000},events:[{sequence:1,type:'TRAVERSAL_INITIALIZED',pseudocodeLineId:'bfs-initialize',state:{kind:'GRAPH_TRAVERSAL',nodeStatuses:{A:'DISCOVERED'},queue:['A'],traversalOrder:[],parents:{},examinedEdge:null},data:{kind:'TRAVERSAL_INITIALIZED',startNode:'A'}},{sequence:2,type:'NODE_DEQUEUED',pseudocodeLineId:'bfs-dequeue',state:{kind:'GRAPH_TRAVERSAL',nodeStatuses:{A:'ACTIVE'},queue:[],traversalOrder:['A'],parents:{},examinedEdge:null},data:{kind:'NODE_DEQUEUED',node:'A'}}]};vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>new Response(JSON.stringify(String(input).endsWith('/api/v2/algorithms')?[...catalog,graphCatalog]:graphTrace),{status:200,headers:{'Content-Type':'application/json'}})));const user=userEvent.setup();render(<App/>);await user.selectOptions(await screen.findByLabelText('Algorithm'),'bfs');expect(screen.getByLabelText('Graph input')).toHaveValue('A');expect(screen.getByLabelText('Start node')).toHaveValue('A');await user.click(screen.getByRole('button',{name:'Visualize'}));expect(await screen.findByRole('img',{name:/Breadth-first traversal graph/})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Next step'}));expect(screen.getByText('A: discovered')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Next step'}));expect(screen.getByText('A: active')).toBeInTheDocument()})

 it('authors a connected graph and submits its derived order and selected start',async()=>{const graphCatalog={id:'bfs',name:'Breadth-First Search',family:'GRAPH_TRAVERSAL',contractVersion:'2.0',constraints:{kind:'GRAPH_TRAVERSAL',minimumNodes:1,maximumNodes:12,maximumEdges:66,nodeLabelPattern:'^[A-Za-z0-9_-]{1,16}$',directed:false,weighted:false}};const graphTrace={apiVersion:'2.0',algorithm:{id:'bfs',name:'Breadth-First Search',family:'GRAPH_TRAVERSAL'},input:{kind:'GRAPH_TRAVERSAL',nodes:['A','C','B','node-one'],edges:[{from:'A',to:'C'},{from:'A',to:'B'},{from:'node-one',to:'C'}],startNode:'C'},result:{kind:'GRAPH_TRAVERSAL',traversalOrder:['C','A','node-one','B'],parents:{A:'C','node-one':'C',B:'A'},unreachableNodes:[],visitedNodeCount:4,edgeExaminationCount:6,maximumQueueSize:2},limits:{maximumEvents:10000},events:[]};const fetchMock=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>(void init,new Response(JSON.stringify(String(input).endsWith('/api/v2/algorithms')?[...catalog,graphCatalog]:graphTrace),{status:200,headers:{'Content-Type':'application/json'}})));vi.stubGlobal('fetch',fetchMock);const user=userEvent.setup();render(<App/>);await user.selectOptions(await screen.findByLabelText('Algorithm'),'bfs');fireEvent.change(screen.getByLabelText('Graph input'),{target:{value:'A-C\nA-B\n"node-one" - C'}});const start=screen.getByLabelText('Start node');expect(Array.from((start as HTMLSelectElement).options).map(option=>option.textContent)).toEqual(['A','C','B','node-one']);await user.selectOptions(start,'C');await user.click(screen.getByRole('button',{name:'Visualize'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));expect(JSON.parse(String(fetchMock.mock.calls[1][1]?.body))).toEqual({kind:'GRAPH_TRAVERSAL',nodes:['A','C','B','node-one'],edges:[{from:'A',to:'C'},{from:'A',to:'B'},{from:'node-one',to:'C'}],startNode:'C'});const graph=await screen.findByRole('img',{name:/Breadth-first traversal graph/});for(const node of ['A','C','B','node-one'])expect(within(graph).getByText(node)).toBeInTheDocument();const edges=graph.querySelectorAll('line');expect(edges).toHaveLength(3);for(const edge of edges)expect(edge).toHaveAttribute('stroke')})
})
